name: Terraform Plan

description: This is a reusable workflow designed to initialise terraform and run terraform plan and upload the plan as an artifact

on:
  workflow_dispatch:
    inputs:
        enable_custom_domain:
          description : "Enable custom domain & ACM Certificate on Cloud front. (True only after DNS validation)"
          required: false
          default: "false"
          type: choice
          options:
            - "true"
            - "false"
    branches:
      - "light"



permissions:
  id-token: write
  contents: read 

defaults:
  run:
    working-directory: ./Infra



jobs:
    terraform-plan:
        runs-on: ubuntu-latest

        env:
          TF_VAR_master_username: ${{secrets.AURORA_USERNAME}}
          TF_VAR_master_password: ${{secrets.AURORA_PASSWORD}}
          TF_VAR_app_db_user: ${{secrets.AURORA_USERNAME}}
          TF_VAR_account_id: ${{secrets.ACCOUNT_ID}}
          TF_VAR_client_id: ${{secrets.CLIENT_ID}}
          TF_VAR_client_secret: ${{secrets.CLIENT_SECRET}}
          TF_VAR_root_domain: ${{secrets.root_domain}} # example.com
          TF_VAR_domain_url: ${{ secrets.DOMAIN_URL}} # https://example.com

        steps:

            - name: Checkout-code
              uses: actions/checkout@v4

            - name: Setup-aws
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ARN}}
                aws-region: ap-south-1
            
            - name: setup-terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: ">= 1.14.0"

            - name: terraform-init
              run: | 
                  terraform init \
                    -backend-config="bucket=${{secrets.state_bucket}}" \
                    -backend-config="key=${{secrets.state_bucket_key}}" \
                    -backend-config="region=${{secrets.state_bucket_region}}" \
                    -backend-config="use_lockfile=true" \
                    -backend-config="encrypt=true"

            #- name: terraform-lock-release
            #  run: terraform force-unlock -force b253094c-a41d-d6fe-ffb8-0d43ef1a53a6

            - name: terraform-plan
              id: plan
              run: |
                set -o pipefail
                terraform plan -no-color -out=tfplan 2>&1 | tee tfplan.log
               
            - name: print-log-lines
              id: print
              if: always()
              run: |
                  echo "==== LAST 200 LINES OF tfplan.log ===="
                  tail -n 200 tfplan.log
            
            - name: upload-logs
              id: logs-artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: tfplan-log
                path: tfplan.log

              

            - name: terraform-plan-show
              if: always()
              run: terraform show tfplan > tfplan.txt


            - name: upload-tfplan-artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: teraform-plan-artifact
                path: ./Infra/tfplan.txt
                if-no-files-found: error

 